# Generated by Django 4.0.5 on 2022-06-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('cab_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cab_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mini'), (2, 'Prime'), (3, 'Suv'), (4, 'Bike'), (5, 'Auto')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_contact_details', models.IntegerField(null=True)),
                ('cab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.cab')),
            ],
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.TextField(blank=True, null=True)),
                ('destination', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.driver')),
            ],
        ),
    ]
