# Generated by Django 4.0.5 on 2022-06-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_alter_tripdetails_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='trip_status',
            field=models.SmallIntegerField(choices=[(0, 'Started'), (1, 'Done'), (2, 'Error')], default=1),
            preserve_default=False,
        ),
    ]
