# Generated by Django 4.0.5 on 2022-06-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_alter_tripdetails_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Started'), (1, 'Done'), (2, 'Error')], null=True),
        ),
    ]
