# Generated by Django 4.0.5 on 2022-06-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_alter_tripdetails_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Started'), (1, 'Done'), (2, 'Error'), (3, 'Available')], default=3),
        ),
    ]
